name: Build and test container
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build image
              run: make docker-build
            - name: Test image
              run: make docker-test
