name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: IMAGE_TAG="ghcr.io/sudo-bot/gh-deployer-container/phpmyadmin" make docker-build

      - name: Test image
        run: IMAGE_TAG="ghcr.io/sudo-bot/gh-deployer-container/phpmyadmin" make docker-test

      - name: Push to GitHub Packages
        run: docker push ghcr.io/sudo-bot/gh-deployer-container/phpmyadmin:latest
