name: Publish Docker image
on:
  release:
    types: [published]
    push:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build action image
        run: IMAGE_TAG="sudo-bot/gh-deployer-container/phpmyadmin" make docker-build

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sudo-bot/gh-deployer-container/phpmyadmin:latest
          registry: docker.pkg.github.com
